Repository BitzKort/HommieStock-Back, pull requests merged in 2024-12, with the labels that each got.

#3 PR fundations project
  .gitignore
  MongoDB_Structure/Collections/Clientes/Clientes.json
  MongoDB_Structure/Collections/Devoluciones/Devoluciones.json
  MongoDB_Structure/Collections/Inventarios/Inventarios.json
  MongoDB_Structure/Collections/Pedidos/Pedidos.json
  MongoDB_Structure/Collections/Productos/Productos.json
  MongoDB_Structure/Collections/Proveedores/Proveedores.json
  MongoDB_Structure/Collections/Reportes/Reportes.json
  MongoDB_Structure/Collections/Tiendas/Tiendas.json
  Pipfile
  Pipfile.lock
  README.md
  main.py
  requirements.txt
  src/Repository/ProductosRepository.py
  src/Repository/__init__.py
  src/Repository/mongodb.py
  src/Routers/ProductosRouter.py
  src/Routers/__init__.py
Labels: enhancement

#8 Feature/mongodb structure
  MongoDB_Structure/Collections/Inventarios/Inventarios.json
  MongoDB_Structure/Collections/Pedidos/Pedidos.json
Labels: enhancement

#10 PR for fix db errors and categorias collection
  Categorias/Categorias.json
  MongoDB_Structure/Collections/Clientes/Clientes.json
  MongoDB_Structure/Collections/Devoluciones/Devoluciones.json
  MongoDB_Structure/Collections/Inventarios/Inventarios.json
  MongoDB_Structure/Collections/Pedidos/Pedidos.json
  MongoDB_Structure/Collections/Productos/Productos.json
  MongoDB_Structure/Collections/Proveedores/Proveedores.json
Labels: bug, enhancement

#11 PR for tienda implementation
  MongoDB_Structure/Collections/Categorias/Categorias.json
  main.py
  src/Routers/TIendasRouter.py
  src/models/Tiendamodels.py
  src/models/__init__.py
  src/schemas/Tiendasschemas.py
  src/schemas/__init__.py
Labels: enhancement

#12 Feature/pydantic casallas
  MongoDB_Structure/Collections/Categorias/Categorias.json
  MongoDB_Structure/Collections/Clientes/Clientes.json
  MongoDB_Structure/Collections/Devoluciones/Devoluciones.json
  main.py
  src/Routers/CategoriasRouter.py
  src/Routers/ClientesRouter.py
  src/Routers/DevolucionesRouter.py
  src/models/Categoriasmodels.py
  src/models/Clientesmodels.py
  src/models/Devolucionesmodels.py
  src/schemas/Categoriaschemas.py
  src/schemas/Clienteschemas.py
  src/schemas/Devolucionesschemas.py
Labels: enhancement

#13 PR some models finished
  MongoDB_Structure/Collections/Proveedores/Proveedores.json
  main.py
  src/Routers/ProductosRouter.py
  src/Routers/ProveedoresRouter.py
  src/Routers/TiendasRouter.py
  src/models/ProductosModels.py
  src/models/ProveedoresModels.py
  src/models/TiendaModels.py
  src/schemas/ProductoSchemas.py
  src/schemas/ProveedoreSchemas.py
  src/schemas/TiendaSchemas.py
Labels: enhancement

#14 Add tags to endpoints
  src/Routers/CategoriasRouter.py
  src/Routers/ClientesRouter.py
  src/Routers/DevolucionesRouter.py
Labels: documentation

#16 Features/requirements casallas
  src/Routers/PedidosRouter.py
  src/Routers/ProveedoresRouter.py
  src/models/PedidosModels.py
  src/models/ProveedoresModels.py
Labels: enhancement

#17 PR requisitos 4 y 5 implementados
  main.py
  src/Routers/ComprasRouter.py
  src/Routers/DevolucionesRouter.py
  src/models/ComprasModels.py
  src/models/DevolucionesModels.py
  src/schemas/DevolucioneSchemas.py
Labels: enhancement

#18 Se crea la funcion de listar inventarios por tienda
  src/Routers/InventariosRouter.py
Labels: enhancement

#20 Se modifica la funcion de crear un inventario
  src/Routers/InventariosRouter.py
Labels: enhancement

#21 PR Feature reportes get all and create report one
  src/Routers/ReportesRouter.py
  src/models/ReportesModels.py
Labels: bug

#22 PR reports implementation
  src/Routers/ProductosRouter.py
  src/Routers/ReportesRouter.py
  src/models/ReportesModels.py
Labels: enhancement
